# Reusable workflow to check for package dependency updates and open a PR to update `Package.resolved` file
name: Package Dependency Check
on:
  workflow_call:
    inputs:
      commit-message:
        required: true
        type: string

jobs:
  swift-package-update-PR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Swift package dependencies
      id: spm-dep-check
      uses: thanhdolong/swift-package-dependencies-check@main
      with:
         isMutating: true
         failWhenOutdated: false
    - name: Create Pull Request
      if: steps.spm-dep-check.outputs.outdatedDependencies  == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: ${{ inputs.commit-message }}
        branch: updatePackageDepedencies
        base: develop
        delete-branch: true
        title: ${{ inputs.commit-message }}
        body: ${{ steps.spm-dep-check.outputs.releaseNotes }}
